/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SummaryService } from "../summary.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SummaryCreateInput } from "./SummaryCreateInput";
import { Summary } from "./Summary";
import { SummaryFindManyArgs } from "./SummaryFindManyArgs";
import { SummaryWhereUniqueInput } from "./SummaryWhereUniqueInput";
import { SummaryUpdateInput } from "./SummaryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SummaryControllerBase {
  constructor(
    protected readonly service: SummaryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Summary })
  @nestAccessControl.UseRoles({
    resource: "Summary",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSummary(
    @common.Body() data: SummaryCreateInput
  ): Promise<Summary> {
    return await this.service.createSummary({
      data: {
        ...data,

        chat: data.chat
          ? {
              connect: data.chat,
            }
          : undefined,
      },
      select: {
        chat: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Summary] })
  @ApiNestedQuery(SummaryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Summary",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async summaries(@common.Req() request: Request): Promise<Summary[]> {
    const args = plainToClass(SummaryFindManyArgs, request.query);
    return this.service.summaries({
      ...args,
      select: {
        chat: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Summary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Summary",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async summary(
    @common.Param() params: SummaryWhereUniqueInput
  ): Promise<Summary | null> {
    const result = await this.service.summary({
      where: params,
      select: {
        chat: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Summary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Summary",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSummary(
    @common.Param() params: SummaryWhereUniqueInput,
    @common.Body() data: SummaryUpdateInput
  ): Promise<Summary | null> {
    try {
      return await this.service.updateSummary({
        where: params,
        data: {
          ...data,

          chat: data.chat
            ? {
                connect: data.chat,
              }
            : undefined,
        },
        select: {
          chat: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Summary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Summary",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSummary(
    @common.Param() params: SummaryWhereUniqueInput
  ): Promise<Summary | null> {
    try {
      return await this.service.deleteSummary({
        where: params,
        select: {
          chat: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
